apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  LIBBA_BACKEND_URL: http://{{ .Release.Name }}-backend
  LIBBA_DATABASE_URL: jdbc:mysql://{{ .Release.Name }}-mysql:{{ .Values.database.service.port }}/{{ .Values.database.database }}