apiVersion: apps/v1
kind: Deployment
metadata:
  name: libba-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libba-frontend
  template:
    metadata:
      labels:
        app: libba-frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://libba-backend:8080"
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      