apiVersion: apps/v1
kind: Deployment
metadata:
  name: libba-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libba-backend
  template:
    metadata:
      labels:
        app: libba-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/library"
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
    