apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.database.service.port }}
      targetPort: 3306
  clusterIP: None  # headless
  selector:
    app: {{ .Release.Name }}-mysql