apiVersion: v1
kind: Service
metadata:
  name: libba-frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
  selector:
    app: libba-frontend