apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: libba-mysql
spec:
  selector:
    matchLabels:
      app: libba-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: libba-mysql
    spec:
      containers:
        - name: libba-mysql
          image: mysql:8.4.5
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.database.password }}
            - name: MYSQL_DATABASE
              value: {{ .Values.database.database }}
            - name: MYSQL_USER
              value: {{ .Values.database.username }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.database.password }}
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
